# Generated by Django 4.1 on 2023-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="worldcup_teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=30)),
                ("stage", models.CharField(max_length=30)),
                ("is_top_3", models.BooleanField(default=False)),
                ("captain", models.CharField(max_length=30)),
                ("goals", models.IntegerField()),
            ],
        ),
    ]
