# Generated by Django 4.1 on 2023-01-14 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldcup_teams",
            name="goals",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(2),
                ]
            ),
        ),
    ]
