# Generated by Django 4.1 on 2023-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0003_captain_alter_worldcup_teams_captain"),
    ]

    operations = [
        migrations.CreateModel(
            name="club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_name", models.CharField(max_length=50)),
                ("league_title_name", models.CharField(max_length=50)),
            ],
        ),
    ]
