# Generated by Django 4.1 on 2023-01-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0004_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captain",
            name="club",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="worldcup.club"
            ),
        ),
    ]
