# Generated by Django 4.1 on 2023-01-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0006_alter_captain_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captain",
            name="club",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="worldcup.club",
            ),
        ),
    ]
