# Generated by Django 4.1 on 2023-01-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0007_alter_captain_club"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="captain",
            name="club",
        ),
        migrations.DeleteModel(
            name="club",
        ),
    ]
