# Generated by Django 4.1 on 2023-01-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0008_remove_captain_club_delete_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldcup_teams",
            name="captain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="worldcup.captain",
            ),
        ),
    ]
