# Generated by Django 4.1 on 2023-01-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0009_alter_worldcup_teams_captain"),
    ]

    operations = [
        migrations.CreateModel(
            name="club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league", models.CharField(max_length=50)),
                ("cup", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="captain",
            name="club",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="worldcup.club",
            ),
        ),
    ]
