# Generated by Django 4.1 on 2023-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0010_club_captain_club"),
    ]

    operations = [
        migrations.CreateModel(
            name="color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_color", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="worldcup_teams",
            name="color",
            field=models.ManyToManyField(null=True, to="worldcup.color"),
        ),
    ]
