# Generated by Django 4.1 on 2023-01-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0011_color_worldcup_teams_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="worldcup_teams",
            name="color",
        ),
        migrations.DeleteModel(
            name="color",
        ),
        migrations.AddField(
            model_name="club",
            name="player",
            field=models.ManyToManyField(to="worldcup.player"),
        ),
        migrations.AddField(
            model_name="worldcup_teams",
            name="player",
            field=models.ManyToManyField(null=True, to="worldcup.player"),
        ),
    ]
