# Generated by Django 4.1 on 2023-01-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0012_player_remove_worldcup_teams_color_delete_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="player",
        ),
        migrations.RemoveField(
            model_name="worldcup_teams",
            name="player",
        ),
        migrations.DeleteModel(
            name="player",
        ),
    ]
